# Generated by Django 4.2.1 on 2023-06-01 16:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, null=True)),
                ('autor', models.CharField(blank=True, max_length=100, null=True)),
                ('co_autor', models.CharField(blank=True, max_length=100, null=True)),
                ('data_cadastro', models.DateField(default=datetime.date.today, null=True)),
                ('emprestado', models.BooleanField(default=False)),
                ('data_emprestimo', models.DateTimeField(blank=True, null=True)),
                ('data_devolucao', models.DateTimeField(blank=True, null=True)),
                ('emprestimo_duracao', models.DurationField(blank=True, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Livros',
                'ordering': ['-data_cadastro'],
            },
        ),
    ]
