# Generated by Django 4.2.1 on 2023-06-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blibioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='capa'),
        ),
    ]
