# Generated by Django 4.2.1 on 2023-06-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blibioteca', '0002_livros_capa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='data_devolucao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livros',
            name='data_emprestimo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
