# Generated by Django 4.2.1 on 2023-06-02 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blibioteca', '0005_alter_livros_data_emprestimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='capa',
            field=models.ImageField(upload_to='capa'),
        ),
    ]
